after building jar, cp to dtest_jars right awway

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2172,6 +2172,7 @@ jobs:
         command: |
           export PATH=$JAVA_HOME/bin:$PATH
           cd ~/cassandra
+          mkdir ~/dtest_jars
           git remote add apache git://github.com/apache/cassandra.git
           for branch in cassandra-2.2 cassandra-3.0 cassandra-3.11 trunk; do
             # check out the correct cassandra version:
@@ -2183,6 +2184,7 @@ jobs:
                 ${ANT_HOME}/bin/ant realclean ; ${ANT_HOME}/bin/ant jar dtest-jar
                 RETURN="$?"
                 if [ "${RETURN}" -eq "0" ]; then
+                    cp build/dtest*.jar ~/dtest_jars
                     break
                 fi
             done
@@ -2198,11 +2200,15 @@ jobs:
               ${ANT_HOME}/bin/ant clean jar dtest-jar
               RETURN="$?"
               if [ "${RETURN}" -eq "0" ]; then
+                  cp build/dtest*.jar ~/dtest_jars
                   break
               fi
           done
-          mkdir ~/dtest_jars
-          cp build/dtest*.jar ~/dtest_jars
+          # Exit, if we didn't build successfully
+          if [ "${RETURN}" -ne "0" ]; then
+              echo "Build failed with exit code: ${RETURN}"
+              exit ${RETURN}
+          fi
           ls -l ~/dtest_jars
         no_output_timeout: 15m
     - persist_to_workspace:
